Channel ID Rules: 153445938151555072 Webhook ID: https://discordapp.com/api/webhooks/290943827370573824/SajlhLINApv9TWQHNgkqvEuXDBJTS_px7EwAH3YxtugYudkDmQ02VaybrezFsd0h2cUk
Channel ID Updates: 160902473882664960 Webhook ID: https://discordapp.com/api/webhooks/290943998292525069/-v8AQ_6rSqfJg87jNd8-ApkT7k_qqpg31ue56r7RQIhA_Kt_bDQcbhxz5XfsNhIO6DG-
Use at website [webhook.tk] with the signing of embed only - Devs Only use.

Webhook.tk created by - DavidNeon / TheNeonGuardian
