@echo off
cd %~dp0
"%SystemDrive%\Python352x64\Scripts\pyinstaller.exe" --console -F -i "%~dp0\VP.ico" -m "%~dp0\manifest.xml" --upx-dir "%~dp0\upx" --distpath "%~dp0\Build\x64" "%~dp0\DecoraterBot.py"
"%~dp0\Build\x64\DecoraterBot.exe"
"%~dp0\Build\x64\DecoraterBot.x64.win32.cpython-352.exe"
del "%~dp0\Build\DecoraterBot\*.*"
"%SystemDrive%\Python351x64\Scripts\pyinstaller.exe" --console -F -i "%~dp0\VP.ico" -m "%~dp0\manifest.xml" --upx-dir "%~dp0\upx" --distpath "%~dp0\Build\x64" "%~dp0\DecoraterBot.py"
"%~dp0\Build\x64\DecoraterBot.exe"
"%~dp0\Build\x64\DecoraterBot.x64.win32.cpython-351.exe"
del "%~dp0\Build\DecoraterBot\*.*"
"%SystemDrive%\Python350x64\Scripts\pyinstaller.exe" --console -F -i "%~dp0\VP.ico" -m "%~dp0\manifest.xml" --upx-dir "%~dp0\upx" --distpath "%~dp0\Build\x64" "%~dp0\DecoraterBot.py"
"%~dp0\Build\x64\DecoraterBot.exe"
"%~dp0\Build\x64\DecoraterBot.x64.win32.cpython-350.exe"
del "%~dp0\Build\DecoraterBot\*.*"
"%SystemDrive%\Python344x64\Scripts\pyinstaller.exe" --console -F -i "%~dp0\VP.ico" -m "%~dp0\manifest.xml" --upx-dir "%~dp0\upx" --distpath "%~dp0\Build\x64" "%~dp0\DecoraterBot.py"
"%~dp0\Build\x64\DecoraterBot.exe"
"%~dp0\Build\x64\DecoraterBot.x64.win32.cpython-344.exe"
del "%~dp0\Build\DecoraterBot\*.*"
"%SystemDrive%\Python343x64\Scripts\pyinstaller.exe" --console -F -i "%~dp0\VP.ico" -m "%~dp0\manifest.xml" --upx-dir "%~dp0\upx" --distpath "%~dp0\Build\x64" "%~dp0\DecoraterBot.py"
"%~dp0\Build\x64\DecoraterBot.exe"
"%~dp0\Build\x64\DecoraterBot.x64.win32.cpython-343.exe"
del "%~dp0\Build\DecoraterBot\*.*"
"%SystemDrive%\Python342x64\Scripts\pyinstaller.exe" --console -F -i "%~dp0\VP.ico" -m "%~dp0\manifest.xml" --upx-dir "%~dp0\upx" --distpath "%~dp0\Build\x64" "%~dp0\DecoraterBot.py"
"%~dp0\Build\x64\DecoraterBot.exe"
"%~dp0\Build\x64\DecoraterBot.x64.win32.cpython-342.exe"
del "%~dp0\Build\DecoraterBot\*.*"
pause