@echo off
cd %~dp0
"%SystemDrive%\Python352\Scripts\pyinstaller.exe" --console -F -i "%~dp0\VP.ico" -m "%~dp0\manifest.xml" --upx-dir "%~dp0\upx" --distpath "%~dp0\Build\x86" "%~dp0\DecoraterBot.py"
"%~dp0\Build\x86\DecoraterBot.exe"
"%~dp0\Build\x86\DecoraterBot.x86.win32.cpython-352.exe"
del "%~dp0\Build\DecoraterBot\*.*"
"%SystemDrive%\Python351\Scripts\pyinstaller.exe" --console -F -i "%~dp0\VP.ico" -m "%~dp0\manifest.xml" --upx-dir "%~dp0\upx" --distpath "%~dp0\Build\x86" "%~dp0\DecoraterBot.py"
"%~dp0\Build\x86\DecoraterBot.exe"
"%~dp0\Build\x86\DecoraterBot.x86.win32.cpython-351.exe"
del "%~dp0\Build\DecoraterBot\*.*"
"%SystemDrive%\Python350\Scripts\pyinstaller.exe" --console -F -i "%~dp0\VP.ico" -m "%~dp0\manifest.xml" --upx-dir "%~dp0\upx" --distpath "%~dp0\Build\x86" "%~dp0\DecoraterBot.py"
"%~dp0\Build\x86\DecoraterBot.exe"
"%~dp0\Build\x86\DecoraterBot.x86.win32.cpython-350.exe"
del "%~dp0\Build\DecoraterBot\*.*"
"%SystemDrive%\Python344\Scripts\pyinstaller.exe" --console -F -i "%~dp0\VP.ico" -m "%~dp0\manifest.xml" --upx-dir "%~dp0\upx" --distpath "%~dp0\Build\x86" "%~dp0\DecoraterBot.py"
"%~dp0\Build\x86\DecoraterBot.exe"
"%~dp0\Build\x86\DecoraterBot.x86.win32.cpython-344.exe"
del "%~dp0\Build\DecoraterBot\*.*"
"%SystemDrive%\Python343\Scripts\pyinstaller.exe" --console -F -i "%~dp0\VP.ico" -m "%~dp0\manifest.xml" --upx-dir "%~dp0\upx" --distpath "%~dp0\Build\x86" "%~dp0\DecoraterBot.py"
"%~dp0\Build\x86\DecoraterBot.exe"
"%~dp0\Build\x86\DecoraterBot.x86.win32.cpython-343.exe"
del "%~dp0\Build\DecoraterBot\*.*"
"%SystemDrive%\Python342\Scripts\pyinstaller.exe" --console -F -i "%~dp0\VP.ico" -m "%~dp0\manifest.xml" --upx-dir "%~dp0\upx" --distpath "%~dp0\Build\x86" "%~dp0\DecoraterBot.py"
"%~dp0\Build\x86\DecoraterBot.exe"
"%~dp0\Build\x86\DecoraterBot.x86.win32.cpython-342.exe"
del "%~dp0\Build\DecoraterBot\*.*"
pause